In [1]:
import numpy as np

In [2]:
heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]


In [4]:
heights_arr = np.array(heights)

In [5]:
heights_arr

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
       182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
       185, 188, 188, 182, 185, 191])

In [6]:
type(heights_arr)

numpy.ndarray

In [10]:
# Heights higher than 188 cm
print((heights_arr > 188).sum())

5


In [13]:
# GET THE SIZE OF THE ARRAY
heights_arr.size

45

In [14]:
# GET THE SHAPE OF THE ARRAY
heights_arr.shape

(45,)

In [15]:
ages = [57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]

In [17]:
ages_arr = np.array(ages)

In [18]:
ages_arr

array([57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56,
       46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62,
       43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70])

In [19]:
heights_and_ages = heights + ages 

In [20]:
heights_and_ages

[189,
 170,
 189,
 163,
 183,
 171,
 185,
 168,
 173,
 183,
 173,
 173,
 175,
 178,
 183,
 193,
 178,
 173,
 174,
 183,
 183,
 180,
 168,
 180,
 170,
 178,
 182,
 180,
 183,
 178,
 182,
 188,
 175,
 179,
 183,
 193,
 182,
 183,
 177,
 185,
 188,
 188,
 182,
 185,
 191,
 57,
 61,
 57,
 57,
 58,
 57,
 61,
 54,
 68,
 51,
 49,
 64,
 50,
 48,
 65,
 52,
 56,
 46,
 54,
 49,
 51,
 47,
 55,
 55,
 54,
 42,
 51,
 56,
 55,
 51,
 54,
 51,
 60,
 62,
 43,
 55,
 56,
 61,
 52,
 69,
 64,
 46,
 54,
 47,
 70]

In [21]:
heights_and_ages_arr = np.array(heights_and_ages)


In [22]:
print(heights_and_ages_arr.shape)

(90,)


In [27]:
heights_and_ages_arr = heights_and_ages_arr.reshape((2,45))

In [30]:
heights_and_ages_arr

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
        182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
        185, 188, 188, 182, 185, 191],
       [ 57,  61,  57,  57,  58,  57,  61,  54,  68,  51,  49,  64,  50,
         48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,
         51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,
         69,  64,  46,  54,  47,  70]])

In [28]:
# Normal Type from Python Built-in 

type(heights_and_ages_arr)

numpy.ndarray

In [29]:
# DTYPE Method

heights_and_ages_arr.dtype

dtype('int64')

In [41]:
# ACCESS the 4th element of the 1st dimension of the np array and changing its value to 165

heights_and_ages_arr[0, 3] = 165

In [43]:
heights_and_ages_arr

array([[189, 170, 189, 165, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
        182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
        185, 188, 188, 182, 185, 191],
       [ 57,  61,  57,  57,  58,  57,  61,  54,  68,  51,  49,  64,  50,
         48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,
         51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,
         69,  64,  46,  54,  47,  70]])