In [1]:
import numpy as np

In [2]:
n, p = [int(x) for x in input().split()]

 2 2


In [3]:
rows_list = []

In [4]:
for _ in range(n):
    row = [float(x) for x in input().split()]
    rows_list.append(row)

 1 1.5
 2 2.9


In [5]:
rows_list

[[1.0, 1.5], [2.0, 2.9]]

In [6]:
proper_array = np.array(rows_list)

In [7]:
proper_array

array([[1. , 1.5],
       [2. , 2.9]])

In [12]:
row_mean_array = np.array([row.mean() for row in proper_array])

In [13]:
row_mean_array

array([1.25, 2.45])

In [15]:
row_mean_array = np.array([round(row,2) for row in row_mean_array])

In [16]:
row_mean_array

array([1.25, 2.45])